# Mikemud base configuration file

name = "Mikemud"
version = "0.0.0"

# Mikemud network configuration.
[telnet]

  # Interface is the address you want the server to bind to. By default it's
  # "localhost" but it can also be set to "0.0.0.0" as well or another IP address
  # to be accessible from outside the server.
  interface = "localhost"

  # Change the port that Mikemud runs on
  port = 8080

  # Change the port the server private port runs on. This private port is only
  # connectable from the machine hosting the server and is the only way to send
  # 'SERVER' messages to all memebers of the game. Other than this, it's the same
  # as connecting to the standard port.
  # TODO: Assess necessity.
  private_port = 8081

# Settings specific to the scripting side of the execution of the program.
[scripting]

  # This section contains settins relevant to server-side script execution.
  # Changing values here can have drastic runtime effects so be careful when
  # modifying from the defaults.
  [scripting.server]

    # This determines how many total server engines there are going to be.
    # It's hard to balance, so be careful. Too many engines would be wasteful,
    # and to little will result in parts of the system queuing up and waiting.
    # The default value was selected as a sane default based on testing during
    # development. But feel free to adjust it for your needs.
    # NOTE: Right now this value is in flux
    engine_pool_size = 10

# DragonMUD uses the bcrypt method for encrypting passwords. This allows you to
# control the cost used when hashing passwords. If you wish to set a static
# cost, you're welcome to. The default cost is 10, but any number between
# 4 and 31 is valid (any input that is not an integer between 4 and 31 and
# "random" is ignored). IT IS NOT RECOMMEND TO CHANGE THIS VALUE. SETTING THIS
# VALUE TO COST VALUES HIGHER THAN 10 (or "random") MAY MAKE IT RUN FOR VERY
# LONG PERIODS OF TIME.
[crypto]

  # cost = 10

# log contains settings specific to the logger for the project such as maximum
# log level and output targets.
[log]

  level = "debug"

  # Define log targets
  # Log type consists of 'terminal' and 'file', the type 'terminal' specifies
  # that you want to log output to a terminal while 'file' denotes an actual
  # file is created to store logs.
  # If you choose 'terminal' as your log type, then the value for target can
  # be either 'terminal' or 'error' which maps to the OS 'stdout' and 'stderr'
  # pointers. if you're not familiar with those details it's best to stick with
  # a type of 'terminal' and a target of 'terminal' here.
  # If you use the type 'file' then the value for target is the path of the
  # logfile you wish to log to.
  [[log.targets]]

    # primary terminal
    type = "terminal"
    target = "terminal"

# Configure the connection information to Neo4j. You can use any environment
# name you want as you can specify which environment to execute when running
# the server. This connects to the default username and password of Neo4j.
[database.development]

  authentication = false
  host = "localhost"
  port = 7687
  username = "neo4j"
  password = "dragonmud"
  connection_max = 10
